name: linux

env:
  LINUX_REF: linux/.git/refs/heads/csi2115-f21
  
on: 
  push:
#     paths:
#       - linux

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: true
    
    
    - name: Download and Unzip
      shell: bash
      run: |
        wget https://github.com/2020147503/linux/archive/`cat $LINUX_REF`.zip
        unzip `cat $LINUX_REF`.zip
    
    - name: Build Linux
      shell: bash
      run: |
        ./build-linux.sh linux-`cat $LINUX_REF` tinyconfig
        
    - name: Remove downloaded files
      shell: bash
      run: |
        rm -rf `cat $LINUX_REF`.zip
        rm -rf linux-`cat $LINUX_REF`
