name: linux

env:
  LINUX_REF: "git submodule | grep linux | awk '{ print $1}'"
  
on: 
  push:
#     paths:
#       - linux

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: true
    
    
    - name: Download and Unzip
      shell: bash
      run: |
        wget https://github.com/2020147503/linux/archive/`$LINUX_REF`.zip
        unzip `$LINUX_REF`.zip
    
    - name: Build Linux
      shell: bash
      run: |
        ./build-linux.sh linux-`$LINUX_REF` tinyconfig
        
    - name: Remove downloaded files
      shell: bash
      run: |
        rm -rf `$LINUX_REF`.zip
        rm -rf linux-`$LINUX_REF`
