name: linux
  
on: 
  push:
#     paths:
#       - linux

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: true
    
    
    - name: Download and Unzip
      shell: bash
      run: |
        wget https://github.com/2020147503/linux/archive/refs/heads/csi2115-f21.zip
        unzip csi2115-f21.zip
    
    - name: Build Linux
      shell: bash
      run: |
        ./build-linux.sh linux-csi2115-f21 tinyconfig
        
    - name: Remove downloaded files
      shell: bash
      run: |
        rm -rf csi2115-f21.zip
        rm -rf linux-csi2115-f21
