name: linux

on: 
  push:
    paths: 
      - linux/**

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Download and Unzip
      shell: bash
      run: |
        wget https://github.com/2020147503/linux/archive/$GITHUB_SHA.zip
        unzip $GITHUB_SHA.zip
    
    - name: Build Linux
      shell: bash
      run: |
        ./build-linux.sh linux-$GITHUB_SHA tinyconfig
        
    - name: Remove downloaded files
      shell: bash
      run: |
        rm -rf $GITHUB_SHA.zip
        rm -rf linux-$GITHUB_SHA
