name: linux

env:
  LINUX_SHA: "`cat linux/.git/refs/heads/csi2115-f21`"
  
on: 
  push:
    paths:
      - linux

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: true
    
    
    - name: Download and Unzip
      shell: bash
      run: |
        wget https://github.com/2020147503/linux/archive/$LINUX_SHA.zip
        unzip $LINUX_SHA.zip
    
    - name: Build Linux
      shell: bash
      run: |
        ./build-linux.sh linux-$LINUX_SHA tinyconfig
        
    - name: Remove downloaded files
      shell: bash
      run: |
        rm -rf $LINUX_SHA.zip
        rm -rf linux-$LINUX_SHA
